server:
  port: 10011
spring:
  application:
    name: eureka-provider
eureka:
  client:
    register-with-eureka: true # 服务注册开关
    fetch-registry: true # 服务发现开关
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:10010/eureka/} # 将自己注册到指定服务注册器
  instance:
    hostname: eureka-provider
    prefer-ip-address: true # 将自己的ip地址注册到eureka-server
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id
