server:
  port: 10020
spring:
  application:
    name: minio-provider

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:10010/eureka/}
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port}


minio:
  endpoint: http://172.16.30.34:9000
  accessKey: admin
  secretKey: admin123456