server:
  port: 10018

spring:
  application:
    name: api-gateway-zuul

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EURAK_SERVER:http://localhost:10010/eureka/}
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port}

zuul:
  host:
    connect-timeout-millis: 10000 # 更改默认超时时间
    socket-timeout-millis: 60000
  semaphore:
    max-semaphores: 200
  routes:
    prefix: /api # 指定统一前缀
    provider-service:
      path: /api-provider/**
      serviceId: eureka-provider
      strip-prefix: true # 请求时将统一前缀剥离掉(默认)

    consumer-service:
      path: /api-consumer/**
      serviceId: eureka-feign-consumer
